- pkg/formulaexec/formula_exec.go
small PR to dynamically follow all symlinks in the /etc/ssl/certs directory and mount them so that they may resolve in the exec/guest container.  Use case is running warpforge on NixOS, which uses multiple layers of symlinks there.
not sure if the helper method is named appropriately or in the correct spot
> formula exec: dynamically follow and mount symlinks for certs in fetch container

- .warpforge/catalog/alpinelinux.org/alpine/mirrors.json
- .warpforge/catalog/alpinelinux.org/alpine/module.json
- cmd/warpforge/catalog.go
- cmd/warpforge/check.go
- cmd/warpforge/ferk.go
- cmd/warpforge/quickstart.go
- cmd/warpforge/run.go
- cmd/warpforge/util.go
- examples/100-formula-parse/example-formulas.md
- examples/110-formula-usage/example-formula-exec.md
- examples/110-formula-usage/example-formula-script.md
- examples/210-plot-parse/example-plots.md
- examples/220-plot-usage/example-plot-exec.md
- examples/500-cli/cli.md
- pkg/formulaexec/formula_exec.go
- pkg/plotexec/plot_exec.go
- pkg/plotexec/plot_exec_test.go
- pkg/workspace/catalog.go
- pkg/workspace/catalog_test.go
- wfapi/catalog.go
- wfapi/formula.go
- wfapi/formula_spec_test.go
- wfapi/formula_test.go
- wfapi/module.go
- wfapi/plot.go
- wfapi/plot_spec_test.go
- wfapi/wfapi.ipldsch
Add "Capsule" types for various types in wfapi. These Capsules allow us to version the type by using an IPLD union, and create breaking changes in the future without losing backwards compatibility. This also fixes all tests and other code which now needs to support the Capsule types.
> Add capsule types

- pkg/formulaexec/formula_exec.go
Fixes silent overriding of the run path to an empty string
when temp dir creation failed.
> Fix runpath being overridden

- Makefile
Adding stty sane after tests should reset the terminal echo settings and
anything else that may have been inadvertently corrupted. This should help
reduce the loss in productivity caused by this problem, however we would
like to find the root cause before it becomes an issue for users.
> Workaround for terminal echo lock

- cmd/warpforge/catalog.go
- pkg/workspace/catalog.go
The schema changes broke adding replays and releases (i.e., `warpforge catalog release` command). This had to do with the order that we were writing things, which has been corrected here.
Also, the `-f` flag on the catalog command now allows for overriding data when needed.
> fix issues with adding replays, allow for overwriting of releases

- cmd/warpforge/catalog.go
- cmd/warpforge/watch.go
Minor fix to prevent nil pointer deref when `--trace` is not set.
> fix trace shutdown calls to prevent nil pointer deref

- pkg/cataloghtml/catalogIndex.tmpl.html
- pkg/cataloghtml/catalogModule.tmpl.html
- pkg/cataloghtml/catalogRelease.tmpl.html
- pkg/cataloghtml/css.css
Style catalogModule.tmpl.html and catalogRelease.tmpl.html to make them easier to navigate.
Specify the platform(s) on which this was tested:
- Brave
- Chrome
- Safari
> style module and release pages

- pkg/workspace/fsdetect.go
- pkg/workspace/fsdetect_test.go
- pkg/workspace/workspace.go
This seems like more correct behavior unless there's a reason that we don't want the stack to stop on a root workspace.
> workspace stack will now end on finding a root workspace

- cmd/warpforge/catalog.go
- go.mod
- go.sum
- pkg/cataloghtml/catalogRelease.tmpl.html
- pkg/cataloghtml/catalogReplay.tmpl.html
- pkg/cataloghtml/cataloghtml.go
- pkg/cataloghtml/css.css
- wfapi/error.go
This adds HTML output for replay plots and download links to release pages. The replay plots are indented, syntax highlighted (using [Chroma](https://github.com/alecthomas/chroma)). Catalog refs in the replay plots are also given links to the relevant release.
It has some issues currently: 
1. The replay link doesn't seem to be clickable (on Firefox at least)
2. Syntax highlighting doesn't follow the style background color.
> HTML Replays & Download Links

- cmd/warpforge/main_test.go
- examples/500-cli/cli.md
- go.mod
- go.sum
Huzzah! :partying_face: 
>With the new additions to testmark, we have a bunch of tests to fix that
weren't actually executing before. This gets us back into a relatively
good state where all the tests pass.
>This change also makes significant changes to how the offline "/net/"
flag works. I.E. Any non-executable children of the parent DirEnt are
copied to the "/net/" DirEnt before execution. This allows a parent with
both online and offline tests to execute and properly pass along
required filesystems, although the parent script/sequence may execute
twice. However, this is _not required_ and a parent of a "/net/"
directory does not need to be executable or have any other children if
the "/net/" DirEnt has executable children. The children copied to the
"/net/" DirEnt must be unique. Any …
> fix up cli tests

- cmd/warpforge/ferk.go
- cmd/warpforge/main_test.go
- examples/500-cli/cli.md
- go.mod
- go.sum
- wfapi/error.go
Relatively minor fix. I will however take a moment to complain about ipld error output.
>execution failed: error from ExecFn is "warpforge-error-plot-invalid: plot file ./plot.wf not parsed: caused by: warpforge-error-serialization: serialization error: unable to deserialize plot: bindnode TODO: len mismatch"
Particularly that last bit: `bindnode TODO: len mismatch` is where the actual "which part of this json is bad" error should be sitting. Playing around with the ipld library, I got it to emit `could not assign string \"pipe:rootfs\": bindnode TODO: len mismatch` which is significantly more useful (oh look I forgot a colon). I'm not sure if that kind of thing is generalizable in any way.
Oh and this is dependent on #39. <- merged and rebased.
> Ferk panic

- .github/workflows/actions.yml
We've been getting a deprecation warning on github actions. This will update the v2 actions to v3. It doesn't appear that any other changes are required.
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-go@v2, actions/upload-artifact@v2
> Update deprecated github actions

- .github/workflows/actions.yml
We previously did two builds on every push to a PR. This performs builds on pushes to PRs, and also on pushes to main/master branch.
> Fix duplicate GHA actions

- cmd/warpforge/internal/util/util.go
- pkg/plotexec/plot_exec.go
- pkg/plumbing/watch/watch.go
- pkg/workspace/catalog.go
- pkg/workspace/workspace.go
- pkg/workspace/workspace_set.go
- wfapi/catalog.go
- wfapi/error.go
- wfapi/plot.go
Bundling catalogs with multiple items from a release would error on the second item because warpforge would be looking in the local workspace version of that release which would only contain the first item. This change allows continuing up the workspace stack to find the item.
> Fixes partial bundle error

- cmd/warpforge/internal/util/plot_templates.go
We used to have a "min catalog" which contained Debian. I've archived it as read-only since we're now defaulting to warpsys everywhere. 
This removes the only remaining reference to `min.warpforge.io` which was used in ferk, and updates it to use the warpsys catalog.
> Change min.warpforge.io catalog to warpsys.org

- pkg/dab/workspace.go
- pkg/formulaexec/formula_exec.go
- pkg/plotexec/plot_exec.go
- pkg/workspace/fsdetect.go
- pkg/workspace/fsdetect_test.go
- pkg/workspace/workspace.go
This stops is from being possible to acceidently get some one else's home workspace as part of your workspace stack.
> Use .warphome as the name for the home workspace

- cmd/warpforge/catalog.go
- cmd/warpforge/check.go
- cmd/warpforge/internal/util/util.go
- cmd/warpforge/quickstart.go
- cmd/warpforge/run.go
- cmd/warpforge/status.go
- examples/200-module-parse/module-names.md
- examples/500-cli/cli.md
- pkg/dab/filetype.go
- pkg/dab/module.go
- pkg/dab/module_test.go
- pkg/plumbing/doc.go
- pkg/plumbing/watch/watch.go
- wfapi/error.go
Also refactors some utility functions by placing them into the dab package. Overall this helps ensure that modules are being validated by centralizing the module file handling.
> Add validation rules to module names

- pkg/dab/workspace.go
- pkg/workspace/fsdetect.go
- pkg/workspace/workspace.go
- wfapi/error.go
Avoiding wrapping errors with serum.Errorf should reduce the duplication of error messages. Additionally marking a bunch of degenerate helper functions as deprecated for future removal. This commit strives to make few behavioral changes outside the primary purpose of reducing message duplication.
> Reduces duplication of errors

- cmd/warpforge/ferk.go
Add usage strings so some guidance appears when running `wf ferk -h`.
(This is sufficiently gimme I'm gonna merge it right away and keep immediately working in the area, but if there are any comments on the helptext, they can get folded into future commits :))
> Document ferk flags.

- cmd/warpforge/catalog.go
- cmd/warpforge/ferk.go
- cmd/warpforge/internal/healthcheck/execute.go
- cmd/warpforge/internal/util/util.go
- cmd/warpforge/run.go
- examples/500-cli/cli.md
- pkg/config/exec_config.go
- pkg/formulaexec/formula_exec.go
- pkg/plumbing/watch/watch.go
With the shuffling of paths, we ended up making mounts relative to the working directory where `warpforge` is executed. This is probably not what we want, since we have Formulas that provide relative paths to the `formula.wf` (or `module.wf` / `plot.wf`) file.
This resolves that by adding a parameter to `FormulaExecConfig` / `PlotExecConfig`. If provided, this specifies the path to use for relative mounts (`FormulaDirectory`).
This also adds a test which uses the CLI testing. This seemed like the best way to build and test a filesystem.
> Make relative mounts relative to formula/module

- cmd/warpforge/internal/util/util.go
- pkg/plotexec/plot_exec.go
- pkg/plumbing/watch/watch.go
- pkg/workspace/fsdetect.go
- pkg/workspace/fsdetect_test.go
- pkg/workspace/workspace.go
- pkg/workspace/workspace_export_test.go
- wfapi/error.go
This includes a test which finds an edge case which will not halt when executing the old FindWorkspace functions.
The goal here is to exercise the FindWorkspace functions thoroughly so we don't find too many more surprises.
This is split off from #58 to reduce PR size.
> add tests and fixes for workspace detection.

- Makefile
- pkg/formulaexec/formula_exec.go
This requires following the symbolic links from the binary path. However, if a source or destination path is repeated we should not mount it twice. This de-duplication might need some tweaking.
I'm not sure if mounting an entire chain of symbolic links is a _good_ idea since you may be mounting unexpected things, but we're already doing that to some extent. For example, I can link `$HOME/gopath/bin/rio` with an absolute path link to `$HOME/repos/warpforge/plugins/rio` and it will mount the directory `$HOME/repos/warpforge/plugins` _inside_ the container to satisfy the link.
Testing this is... not easy. We would need both an `os.DirFS` and a `MapFS` with a `Stat` implementation which doesn't follow links like `Lstat`. Or we can project onto an actual filesystem and run tests from there …
> allow rio to be mounted via symbolic links

- cmd/warpforge/ferk.go
- cmd/warpforge/internal/util/util.go
- cmd/warpforge/status.go
- pkg/dab/find.go
- pkg/dab/find_test.go
- pkg/dab/guess.go
- pkg/dab/guess_test.go
- pkg/dab/module.go
- pkg/plumbing/watch/watch.go
- pkg/testutil/turtletb/tb.go
Makes some changes to how Ferk works:
1. Allows the plot specified to be a plot file or a module directory
2. Modify ferk to run a specific step in the plot (default: `ferk`)
Most notably, this adds `dab.FindActionableFromFS` which finds actionable files (modules, formulas, plots) in a standard way. This is only use by `ferk` as of this PR, but will be integrated into other subcommands (notably, `run`) in the near future :)
> Ferk tweaks

- app/enter/ferk_cli.go
A couple places had the "ferk" step hard-coded which caused a segfault on custom step names.
> fix the --cmd flag for ferk to not segfault on custom step names

- app/plan/generators.go
Currently warplark will emit errors for bad starlark on stderr and
warpforge will consume that output silently. Ideally we decorate it
appropriately before emitting it blindly but this is workable.
> pass through stderr from plan generate execution

- app/testutil/guidmapper.go
- app/testutil/testutil.go
- examples/500-cli/cli.md
- go.mod
- go.sum
Changes regenerated testmark to replace GUIDs with order-determistic
GUIDs and sets timestamps to a constant. This should help reduce git
diff noise while still appearing mostly correct to readers.
> Normalize regen

- app/_docs/warpforge-catalog.md
- app/catalog/catalog_cli.go
This should make catalog content discovery much easier from the command line.
> Enhance catalog ls to traverse down catalogs.
